### ISSUE TITLE
How does merging work?

### ISSUE THREAD

**Issue by djakubosky** [zeeev/mergeSVcallers#5]
Hi! glad to see a tool for this purpose, merging call sets is a headache.  I am curious as to whether this tool will merge based on correlation between samples, is there any criteria for a merge other than distance and overlap? 

Thanks!

**Comment by zeeev** [comment]
@djakubosky you can merge within samples and then merge across datasets.  Does that answer your question?

**Comment by djakubosky** [comment]
So basically, the method doesn't consider correlation of genotypes between samples, but rather overlap of SVs both within and between samples to create a single set of less "redundant" positions.
